name: Container
on:
  push:
    branches:
      - main
    paths:
      - "code/container/**"
      - ".github/workflows/_containerTemplate.yml"
  schedule:
    - cron: "0 20 * * 5" # Run every Friday at 8 PM

  pull_request:
    branches:
      - main
    paths:
      - "code/container/**"
      - ".github/workflows/_containerTemplate.yml"

jobs:
  build_and_publish:
    uses: ./.github/workflows/_containerTemplate.yml
    name: "Build & Publish"
    with:
      environment: "dev"
      working_directory: "./code/container"
      registry_uri: "ghcr.io"
      image_namespace_name: "PerfectThymeTech"
      image_name: "ShirAgentAzure"
    secrets:
      USER_NAME: ${{ github.actor }}
      PASSWORD: ${{ secrets.GITHUB_TOKEN }}
